//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelegramBot.Classes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSelectedVoice
    {
        public int UserNum { get; set; }
        public string VoiceId { get; set; }
        public int UserID { get; set; }
    }
}
